### ISSUE TITLE
[ERROR] Package has no install method: python-click-plugins

### ISSUE THREAD

**Issue by catalinalb** [click-contrib/click-plugins#30]
Hi I am using ubuntu 20.04 LTS. 
I am going the long bumpy paths of installing gnuradio with pybombs. I did came accross this error: 
[ERROR] Package has no install method: python-click-plugins

I did installed it with pip also directly from source as described and run also sudo ldconfig but the error remains... :( 

Please help!!

Thank you

**Comment by geowurster** [comment]
This is either caused by a problem with the Ubuntu `python-click-plugins` package, which I do not own, or `PyBOMBS`. I am not familiar with `PyBOMBS` but https://github.com/gnuradio/pybombs/issues/555, specifically https://github.com/gnuradio/pybombs/issues/555#issuecomment-560035098, seems to be related to your issue.
